### ISSUE TITLE
Mock the HTTP client in tests

### ISSUE THREAD

**Issue by tesaguri** [kitsune-soc/kitsune#294]
Some of current test code makes HTTP requests to remote servers, for example:

https://github.com/kitsune-soc/kitsune/blob/a098f0a1647cff01d2b8b110a2b942ed73bcddea/kitsune/src/activitypub/fetcher.rs#L300-L303

But this kind of test is not quite reproducible since it would break if the server went down or you removed the account. Also, it might be slow and possibly overload the server, and you'll need to find another server in the wild if you are going to test against a feature the current target server doesn't support (especially, #285 is in my mind).

Fortunately, Kitsune is using Tower's middleware abstraction for its HTTP client, which is easy to replace with a mock client. That can be achieved by adding a new finalizer method to `kitsune_http_client::ClientBuilder` that takes a mock HTTP client to wrap. With the new method (let's call it `build_with_client` for now) the test code will look like the following pseudo code:

```rust
let mock_client = tower::service_fn(|req| async move {
    let res = create_mock_response();
    Ok(res)
});
let client = Client::builder()/* ... */.build_with_client(mock_client);
let fetcher = Fetcher::builder().client(client)/* ... */.build();

let user = fetcher
    .fetch_actor("https://corteximplant.com/users/0x0".into())
    .await
    .expect("Fetch actor");
```

If this idea looks good to you, I'd be happy to work on a pull request!

**Comment by aumetra** [comment]
Yep, mocking the test client is a good idea. Also thanks for the offer to implement it!  
This is definitely a great suggestion and a really neat improvement!

We actually hit the issue that we used the account of a friend of mine and they deleted theirs and our tests broke. Also the tests are broken inside of `nix build` since they aren't allowing any access to things like the filesystem or network, to keep things reproducible.

**Comment by aumetra** [comment]
I'm just gonna assign you this issue, if that's okay
