### ISSUE TITLE
[Swagger] Could not resolve reference: Could not resolve pointer: /components/schemas/Timestamp does not exist in document

### ISSUE THREAD

**Issue by Zeerooth** [kitsune-soc/kitsune#360]
Steps to reproduce:
1. Run kitsune
2. Go to http://localhost:5000/swagger-ui/
3. Expand the `Account` schema, for example

**Comment by aumetra** [comment]
I have an idea what the issue is. We are using [`iso8601-timestamp`](https://docs.rs/iso8601-timestamp/0.2.12/iso8601_timestamp/index.html) for our timestamp handling (it's small and the de-/serialization is *incredibly* fast) which doesn't implement the `utoipa` traits.

I'm gonna check whether we can hack around that somehow on our side or whether I have to submit a PR for the `utoipa` support

**Comment by Zeerooth** [comment]
Indeed, unfortunately `utoipa` only support `chrono` and `time` natively.

One of the possible solutions I've seen is casting the type into something else that `utoipa` supports using
```rust
#[schema(value_type = String)]
pub created_at: Timestamp,
```
for example (or it could be like chrono DateTime as a target type I suppose)
